# -*- mode: python; -*-

Import("env")

env = env.Clone()

env.Library(
    target= 'storage_biggie',
    source= [
    ],
)

env.CppUnitTest(
    target='store_test',
    source=[
        'store_test.cpp',
    ],
)
