# -*- mode: python; -*-

Import("env")

env = env.Clone()

env.Library(
    target= 'storage_biggie_core',
    source= [
        'store.cpp',
    ],
)

env.CppUnitTest(
    target='store_test',
    source=[
        'store_test.cpp',
    ],
    LIBDEPS=[
        'storage_biggie_core',
    ],
)
