# -*- mode: python; -*-

Import("env")

env = env.Clone()

env.CppUnitTest(
    target='radix_biggie_store_test',
    source=[
        'radix_store_test.cpp',
    ],
)

env.CppUnitTest(
    target='storage_biggie_store_test',
    source=[
        'store_test.cpp',
    ],
)
